# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3242fdf1b33f3fbd306f787c15f36c275de177ab9d18466a6aa0451abad1bde9816a4ceeffed1960b253d485a05e9d8151e0811feb912394612fc94e58b1d012

test:
  secret_key_base: c716d7f0e2f1fba601b8c07b9106be6ee4fac7608a47e7c8d6aab7f919fb6b6bd026f9aa7eefe0d714cd9ef2344114768f5ef096f60915b4b8ed45b3e38d4d45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
